---
title: "R Notebook"
output: html_notebook
---


```{r}
library(tidyverse)
library(sf)
library(raster)
load("masterdataframe.RData")
```

```{r}
landcover <- raster("spatial/lcm2007gb25m_.tif")

plot(landcover)
```


```{r}
# what are the min/max coords for our data?
minmax <- dftidy_wide %>% 
  dplyr::select(easting, northing) %>% 
  summarise_all(
    list(min = min,
         max = max)
  )

minmax

points <- dftidy_wide %>% 
  distinct(easting, northing) %>% 
  as.matrix()

```

```{r}
uk <- read_sf("spatial/Countries_December_2017_Full_Clipped_Boundaries_in_Great_Britain.shp")
```


```{r}
plot(landcover, xlim = c(300000, 400000), ylim = c(100000, 200000))
plot(uk)
plot(points)

rasterToPolygons(landcover)


```





```{r}
# # Voronai mosaic to visualise distance matrix
# library(tripack)
# plot(voronoi.mosaic(x = points[,"easting"], y = points[,"northing"], duplicate="remove"))
```


```{r}
# # Visualising the distance matrix of sites and plots
# dist_m <- points %>% dist() %>% as.matrix()
# dist_mi <- 1/dist_m # one over, as qgraph takes similarity matrices as input
# library(qgraph)
# jpeg('example_forcedraw.jpeg', width=10, height=10, units = "in", res = 320)
# qgraph(dist_mi, layout='spring', vsize=3)
# dev.off()
```




























